### ISSUE TITLE
Close button is not visible

### ISSUE THREAD

**Issue by goldim** [sqville/ville.Fluent#1]
![изображение](https://github.com/sqville/ville.Fluent/assets/22189134/397bbca3-c83f-4d35-9ddf-64fbee15881b)

**Comment by sqville** [comment]
@goldim I replaced with a different approach. The different approach has been committed to master. This is also scheduled to be a part of the v2.1 release. Not sure if this is a bug in v2 though

**Comment by sqville** [comment]
Not a theme issue.
