### ISSUE TITLE
Warnings about missing resourses

### ISSUE THREAD

**Issue by goldim** [sqville/ville.Fluent#2]
![изображение](https://github.com/sqville/ville.Fluent/assets/22189134/7a436237-ef2c-445b-9edd-96f207f0492d)

**Comment by sqville** [comment]
@goldim Not exactly sure how this is a bug. All of those files exist in the theme. I am not able to reproduce

**Comment by goldim** [comment]
When I run `qx serve` in theme folder. All of these resources work and are loaded fine but if I use your theme as package from package system repository I get these errors. And notice that broken only `svg` and `gif` files. Probably the problem is in qooxdoo.

**Comment by goldim** [comment]
I found. This is wrong path to resource files in asset directive.

**Comment by sqville** [comment]
@goldim I did some more hunting and found that theme switching and dynamically named resources do not play well with each other. scrollbar buttons and ascending descending table column icons are examples. Until I can come up with a proposed solution, I am going to include the named resources in my Image.js file.
