### ISSUE TITLE
Tooltip font color

### ISSUE THREAD

**Issue by goldim** [sqville/ville.Fluent#3]
Looks like tooltip colors broken.
![Снимок экрана от 2024-04-10 18-47-50](https://github.com/sqville/ville.Fluent/assets/22189134/16c84f0d-7dac-40b9-8d36-cd2900967016)

**Comment by sqville** [comment]
@goldim tooltip appearance and decorator entries are referencing old color names which i left in the ville.theme.fluent.Common color list just in case. Fix is in place in my local copy. Just need to decide how the invalid state should work for tooltip and other controls. Once i do i will update here.

**Comment by sqville** [comment]
@goldim included fix in v1.1.0 release
