### ISSUE TITLE
Close and restore button colors differ

### ISSUE THREAD

**Issue by goldim** [sqville/ville.Fluent#6]
![изображение](https://github.com/sqville/ville.Fluent/assets/22189134/fc9742cd-245e-4140-a617-de970b9b321f)

Button colors differs for window buttons. I suggest to use white colors for theme.

**Comment by sqville** [comment]
Fixed. Will be a part of the next release

**Comment by sqville** [comment]
@goldim they should be the same in v1.1.0 release
