### ISSUE TITLE
Web font icon color of dark version

### ISSUE THREAD

**Issue by goldim** [sqville/ville.Fluent#7]
![изображение](https://github.com/sqville/ville.Fluent/assets/22189134/7a575522-175f-4496-952e-68f563640e7f)

I think white is better. All dark themes I've met there are white by default.

**Comment by sqville** [comment]
As a preference, ville themes do not use font based icons. However, font icons are an important part of the qx framework and the MS Fluent design system. Therefore, treating this as a bug and will be a part of the next release

**Comment by sqville** [comment]
@goldim I think i fixed this in v1.1.0 release. Please retest. Since it's a font it has to be the textColor appearance entry in either the "image" entry or specifically in the "button" entry
